#! /bin/bash

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
~/.config/bspwm/autostart.sh
#feh --bg-fill ~/Pictures/kyojin.jpg &

# Functions
multimonitors()
{
   start_from=1
   monitors_connected=$(bspc query -M | wc -l)
   per_monitor=$(( 8 / monitors_connected ))
   for monitor in $(bspc query -M); do
      bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor -
      1)))
      start_from=$(( start_from + per_monitor ))
   done
}

multibar()
{
   #pkill polybar
   #while pgrep -x polybar >/dev/null; do sleep 1; done
   killall -q polybar
   while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
   xrandr -q | awk '/ connected / {print $1}' | while read -r monitor _; do
      #polybar -r "$monitor" &
      echo "---" | tee -a /tmp/polybar_${monitor}.log
      polybar -r $monitor 2>&1 | tee -a /tmp/polybar_${monitor}.log & disown
   done
}

# Setting up monitors
#xrandr --output VGA-1 --mode 1366x768 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --rotate normal --right-of VGA-1
xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output VGA-1 --mode 1920x1080 --rotate normal --right-of HDMI-1

# Desktops/Workspaces
bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor VGA-1 -d 5 6 7 8
#multimonitors
#multibar &

# Coloring
bspc config normal_border_color		      "#282A36"
bspc config active_border_color	        "#44475A"
bspc config focused_border_color	      "#6272A4"
bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"

# Config
#bspc config border_radius                 6
bspc config border_width                  1
bspc config window_gap                    6
bspc config top_padding                   2
bspc config bottom_padding                2
bspc config -m VGA-1 bottom_padding       30
bspc config -m HDMI-1 top_padding         30
bspc config left_padding                  2
bspc config right_padding                 2
bspc config single_monocle                true
bspc config click_to_focus                button1
bspc config split_ratio                   0.55
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

# Rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Mintstick.py state=floating focus=on
bspc rule -a Gnome-disks state=floating
bspc rule -a Gnome-font-viewer state=floating follow=on focus=on
bspc rule -a Gpick state=floating
bspc rule -a Imagewriter state=floating follow=on
bspc rule -a Font-manager state=floating focus=on
bspc rule -a xpad state=floating focus=on sticky=on
bspc rule -a indicator-stickynotes state=floating focus=on sticky=on
bspc rule -a qt5ct state=floating
bspc rule -a mate-control-center state=floating follow=on focus=on
bspc rule -a mate-notification-daemon state=floating
bspc rule -a Usb-creator-gtk state=floating
bspc rule -a Wine state=floating follow=on
bspc rule -a Lightdm-settings state=floating
bspc rule -a Yad state=floating
bspc rule -a vlc desktop="^4" follow=on focus=on
bspc rule -a Celluloid desktop="^4" follow=on focus=on
bspc rule -a Copying state=floating
bspc rule -a Deleting state=floating
bspc rule -a Moving state=floating
bspc rule -a gimp-toolbox-color-dialog state=floating
bspc rule -a pop-up state=floating focus=on
bspc rule -a Preferences state=floating
bspc rule -a setup state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a GParted state=floating focus=on
bspc rule -a Simple-scan state=floating
bspc rule -a Kernels state=floating focus=on follow=on
bspc rule -a xterm state=floating focus=on
bspc rule -a urxvt state=floating focus=on
bspc rule -a ulauncher state=floating border=off focus=on sticky=on

# Focus
bspc rule -a Mate-terminal focus=on
bspc rule -a kitty focus=on
bspc rule -a alacritty focus=on

# Assign
bspc rule -a Firefox desktop="^3" follow=on focus=on
bspc rule -a firefox desktop="^3" follow=on focus=on
bspc rule -a Vlc desktop="^4" follow=on focus=on
bspc rule -a celluloid desktop="^4" follow=on focus=on
bspc rule -a Rhythmbox desktop="^6" follow=on focus=on
bspc rule -a rhythmbox desktop="^6" follow=on focus=on
bspc rule -a Thunderbird desktop="^7" follow=on focus=on
bspc rule -a thunderbird desktop="^7" follow=on focus=on

# Special Rules
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

#open Funny Java Things
wmname LG3D &

