#! /bin/bash

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
~/.config/bspwm/autostart.sh
#feh --bg-fill ~/Pictures/kyojin.jpg &

# Setting up monitors
xrandr --output VGA-1 --mode 1366x768 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --rotate normal --right-of VGA-1

# Desktops/Workspaces
bspc monitor HMDI-1 -d 1 2 3 4
bspc monitor VGA-1 -d 5 6 7 8

# Coloring
bspc config normal_border_color		      "#282A36"
bspc config active_border_color	          "#44475A"
bspc config focused_border_color	      "#6272A4"
bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"

# Config
#bspc config border_radius                 6
bspc config border_width                  2
bspc config window_gap                    6
bspc config top_padding                   2
bspc config bottom_padding                2
bspc config -m VGA-1 bottom_padding       30
bspc config -m HDMI-1 top_padding         30
bspc config left_padding                  2
bspc config right_padding                 2
bspc config single_monocle                true
bspc config click_to_focus                button1
bspc config split_ratio                   0.55
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

# Rules
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Blueberry.py state=floating
bspc rule -a Mintstick.py state=floating focus=on
bspc rule -a Gnome-disks state=floating
bspc rule -a Gnome-font-viewer state=floating follow=on focus=on
bspc rule -a Gpick state=floating
bspc rule -a Imagewriter state=floating follow=on
bspc rule -a Font-manager state=floating focus=on
bspc rule -a xpad state=floating focus=on sticky=on
bspc rule -a indicator-stickynotes state=floating focus=on sticky=on
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating follow=on focus=on
bspc rule -a Xfce4-settings-manager follow=on focus=on state=floating
bspc rule -a mate-control-center state=floating follow=on focus=on
bspc rule -a mate-notification-daemon state=floating
bspc rule -a Xfce4-taskmanager state=floating focus=on
bspc rule -a Usb-creator-gtk state=floating
bspc rule -a Wine state=floating follow=on
bspc rule -a Lightdm-settings state=floating
bspc rule -a Yad state=floating
bspc rule -a vlc desktop="^4" follow=on focus=on
bspc rule -a xplayer desktop="^4" follow=on focus=on
bspc rule -a Celluloid desktop="^4" follow=on focus=on
bspc rule -a Copying state=floating
bspc rule -a Deleting state=floating
bspc rule -a Moving state=floating
bspc rule -a gimp-toolbox-color-dialog state=floating
bspc rule -a pop-up state=floating focus=on
bspc rule -a Preferences state=floating
bspc rule -a setup state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a GParted state=floating focus=on
bspc rule -a Simple-scan state=floating
bspc rule -a Kernels state=floating focus=on follow=on
bspc rule -a xterm state=floating focus=on
bspc rule -a urxvt state=floating focus=on
bspc rule -a ulauncher state=floating border=off focus=on

# Focus
bspc rule -a Mate-terminal focus=on
bspc rule -a kitty focus=on

# Assign
bspc rule -a Nemo desktop="^1" follow=on focus=on
bspc rule -a nemo desktop="^1" follow=on focus=on
bspc rule -a Caja desktop="^1" follow=on focus=on
bspc rule -a caja desktop="^1" follow=on focus=on
bspc rule -a xed desktop="^2" follow=on focus=on
bspc rule -a Gedit desktop="^2" follow=on focus=on
bspc rule -a gedit desktop="^2" follow=on focus=on
bspc rule -a Sublime desktop="^2" follow=on focus=on
bspc rule -a subl desktop="^2" follow=on focus=on
bspc rule -a Code desktop="^2" follow=on focus=on
bspc rule -a code desktop="^2" follow=on focus=on
bspc rule -a Firefox desktop="^3" follow=on focus=on
bspc rule -a firefox desktop="^3" follow=on focus=on
bspc rule -a Brave-Browser desktop="^3" follow=on focus=on
bspc rule -a brave-browser desktop="^3" follow=on focus=on
bspc rule -a Vlc desktop="^4" follow=on focus=on
bspc rule -a celluloid desktop="^4" follow=on focus=on
bspc rule -a Xplayer desktop="^4" follow=on focus=on
bspc rule -a pinta desktop="^5" follow=on focus=on
bspc rule -a Pinta desktop="^5" follow=on focus=on
bspc rule -a Eog desktop="^5" follow=on focus=on
bspc rule -a eog desktop="^5" follow=on focus=on
bspc rule -a feh desktop="^5" follow=on focus=on
bspc rule -a Rhythmbox desktop="^6" follow=on focus=on
bspc rule -a rhythmbox desktop="^6" follow=on focus=on
bspc rule -a cmus desktop="^6" follow=on focus=on
bspc rule -a ncmpcpp desktop="^6" follow=on focus=on
bspc rule -a Thunderbird desktop="^7" follow=on focus=on
bspc rule -a thunderbird desktop="^7" follow=on focus=on
bspc rule -a Geary desktop="^7" follow=on focus=on
bspc rule -a geary desktop="^7" follow=on focus=on

# Special Rules
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

#open Funny Java Things
wmname LG3D &

